// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// PokemonController is an autogenerated mock type for the PokemonController type
type PokemonController struct {
	mock.Mock
}

// CatchPokemon provides a mock function with given fields: w, r
func (_m *PokemonController) CatchPokemon(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CreatePokemon provides a mock function with given fields: w, r
func (_m *PokemonController) CreatePokemon(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// FilterPokemons provides a mock function with given fields: w, r
func (_m *PokemonController) FilterPokemons(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetAllPokemon provides a mock function with given fields: w, r
func (_m *PokemonController) GetAllPokemon(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetPokemonById provides a mock function with given fields: w, r
func (_m *PokemonController) GetPokemonById(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
