// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	utils "github.com/carlos-garibay/Go-Dispatch-Bootcamp/utils"
	mock "github.com/stretchr/testify/mock"
)

// IworkerPool is an autogenerated mock type for the IworkerPool type
type IworkerPool struct {
	mock.Mock
}

// AddWorker provides a mock function with given fields: w
func (_m *IworkerPool) AddWorker(w utils.Iworker) {
	_m.Called(w)
}

// Close provides a mock function with given fields:
func (_m *IworkerPool) Close() {
	_m.Called()
}

// GetWorkers provides a mock function with given fields:
func (_m *IworkerPool) GetWorkers() []utils.Iworker {
	ret := _m.Called()

	var r0 []utils.Iworker
	if rf, ok := ret.Get(0).(func() []utils.Iworker); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]utils.Iworker)
		}
	}

	return r0
}

// Run provides a mock function with given fields:
func (_m *IworkerPool) Run() {
	_m.Called()
}
