// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	model "github.com/carlos-garibay/Go-Dispatch-Bootcamp/model"
	mock "github.com/stretchr/testify/mock"
)

// Iworker is an autogenerated mock type for the Iworker type
type Iworker struct {
	mock.Mock
}

// Execute provides a mock function with given fields: in, out
func (_m *Iworker) Execute(in <-chan []string, out chan<- *model.Pokemon) {
	_m.Called(in, out)
}

// Id provides a mock function with given fields:
func (_m *Iworker) Id() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
